# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 009b98889be458cbdf24fe6c906c537cb4616284c3ce16e9ac9a936e883f8ec70bed7de5efd3c3f384354fceb41975c0a7d3a2a3586dfc679300599e08013f18

test:
  secret_key_base: 27e2a0e64a973d4f4ce811bf79fe0dfd5e0198d551aabfa1a6721d8600a4e13246a6811dab9fd3bac77fea9b1e91dc1de5b0beefdd4f22a079a86d8184b80d48

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
